// Package whispersrc compiles the vendored whisper.cpp source via cgo.
//
// WHISPER_VERSION / PARAKEET_VERSION are normally injected by CMake; because
// cgo forbids '"' in #cgo flags they are force-included from
// whisper-version-defs.h (generated by scripts/vendor-whisper.sh).
package whispersrc

// #cgo CPPFLAGS: -I${SRCDIR}/../include -I${SRCDIR}/../../../ggml/cvendor/include -I${SRCDIR} -DNDEBUG -include ${SRCDIR}/whisper-version-defs.h
// #cgo CXXFLAGS: -O3 -std=c++17 -fPIC -pthread
// #cgo linux CPPFLAGS: -D_XOPEN_SOURCE=600 -D_GNU_SOURCE
// #cgo darwin CPPFLAGS: -D_XOPEN_SOURCE=600 -D_DARWIN_C_SOURCE
// #cgo windows CXXFLAGS: -Wa,-mbig-obj
import "C"
