// Package ggmlsrc compiles the vendored ggml core sources via cgo.
// C sources in this directory are synced by scripts/vendor-whisper.sh;
// this file is hand-maintained and survives re-vendoring.
//
// GGML_VERSION / GGML_COMMIT are normally injected by CMake; because cgo
// forbids '"' in #cgo flags they are force-included from ggml-version-defs.h
// (generated by scripts/vendor-whisper.sh). The _XOPEN_SOURCE / _GNU_SOURCE /
// _DARWIN_C_SOURCE feature-test macros mirror ggml/src/CMakeLists.txt and are
// required because we compile with a strict -std (they expose M_PI, getline,
// posix_memalign and the Linux CPU-affinity APIs).
package ggmlsrc

// #cgo CPPFLAGS: -I${SRCDIR}/../include -I${SRCDIR} -DNDEBUG -DGGML_USE_CPU -include ${SRCDIR}/ggml-version-defs.h
// #cgo CFLAGS: -O3 -std=c11 -fPIC -pthread
// #cgo CXXFLAGS: -O3 -std=c++17 -fPIC -pthread
// #cgo linux CPPFLAGS: -D_XOPEN_SOURCE=600 -D_GNU_SOURCE
// #cgo darwin CPPFLAGS: -D_XOPEN_SOURCE=600 -D_DARWIN_C_SOURCE -DGGML_USE_METAL -DGGML_METAL_EMBED_LIBRARY -DGGML_USE_ACCELERATE -DACCELERATE_NEW_LAPACK -DACCELERATE_LAPACK_ILP64
// #cgo darwin LDFLAGS: -framework Accelerate -framework Metal -framework MetalKit -framework Foundation
// #cgo linux LDFLAGS: -lm -lstdc++ -pthread
// #cgo windows CXXFLAGS: -Wa,-mbig-obj
// #cgo windows LDFLAGS: -lm -lstdc++ -pthread -static-libgcc -static-libstdc++
import "C"
