#!/usr/bin/env bash
# Vendors ggml C/C++ sources (core, CPU backend, Metal backend) into
# internal/ggml/cvendor/, from the pinned llama.cpp tag — llama.cpp's ggml
# sync is the most current, and whisper.cpp must build against the same
# version (see scripts/vendor-versions.env). Go shim files (*.go) and
# VERSION are preserved; everything else is synced.
# Usage: scripts/vendor-ggml.sh [llama.cpp tag]
set -euo pipefail

cd "$(dirname "$0")/.."
source scripts/vendor-versions.env
TAG="${1:-$LLAMA_TAG}"
DEST="internal/ggml/cvendor"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

git clone --depth 1 --branch "$TAG" https://github.com/ggml-org/llama.cpp "$TMP/l"
SRC="$TMP/l/ggml"

if [ -d "$DEST" ]; then
  find "$DEST" -type f ! -name '*.go' -delete
  find "$DEST" -type d -empty -delete
fi
mkdir -p "$DEST/include" "$DEST/src"

cp "$SRC/include/"*.h "$DEST/include/"
find "$SRC/src" -maxdepth 1 -type f \
  \( -name '*.c' -o -name '*.cpp' -o -name '*.h' \) \
  -exec cp {} "$DEST/src/" \;
cp -r "$SRC/src/ggml-cpu" "$DEST/src/"

# Metal backend (darwin). Layout moved over time: directory or flat files.
if [ -d "$SRC/src/ggml-metal" ]; then
  cp -r "$SRC/src/ggml-metal" "$DEST/src/"
else
  mkdir -p "$DEST/src/ggml-metal"
  cp "$SRC/src/ggml-metal."* "$DEST/src/ggml-metal/" 2>/dev/null || true
fi

# Assembly stub embedding the Metal shader source into the binary
# (GGML_METAL_EMBED_LIBRARY expects these symbols). Mirror upstream CMake:
# inline ggml-common.h and ggml-metal-impl.h to make the shader source
# self-contained (it is compiled by Metal at runtime with no include paths).
METAL_SRC="$(find "$DEST/src/ggml-metal" -name 'ggml-metal.metal' | head -1)"
if [ -n "$METAL_SRC" ]; then
  METAL_DIR="$(dirname "$METAL_SRC")"
  sed -e "/__embed_ggml-common.h__/r $DEST/src/ggml-common.h" \
      -e '/__embed_ggml-common.h__/d' "$METAL_SRC" \
    | sed -e "/#include \"ggml-metal-impl.h\"/r $METAL_DIR/ggml-metal-impl.h" \
          -e '/#include "ggml-metal-impl.h"/d' \
    > "$METAL_DIR/ggml-metal-embed.metal"
  cat > "$METAL_DIR/ggml-metal-embed.s" <<EOF
.section __DATA,__ggml_metallib
.globl _ggml_metallib_start
_ggml_metallib_start:
.incbin "ggml-metal-embed.metal"
.globl _ggml_metallib_end
_ggml_metallib_end:
EOF
fi

# Version macros normally injected by CMake; cgo forbids '"' in #cgo flags,
# so generate a force-included header instead.
GGML_MAJOR="$(sed -n 's/.*set(GGML_VERSION_MAJOR \([0-9][0-9]*\)).*/\1/p' "$SRC/CMakeLists.txt")"
GGML_MINOR="$(sed -n 's/.*set(GGML_VERSION_MINOR \([0-9][0-9]*\)).*/\1/p' "$SRC/CMakeLists.txt")"
GGML_PATCH="$(sed -n 's/.*set(GGML_VERSION_PATCH \([0-9][0-9]*\)).*/\1/p' "$SRC/CMakeLists.txt")"
cat > "$DEST/src/ggml-version-defs.h" <<EOF
// Generated by scripts/vendor-ggml.sh. Do not edit.
#pragma once
#ifndef GGML_VERSION
#define GGML_VERSION "${GGML_MAJOR}.${GGML_MINOR}.${GGML_PATCH}"
#endif
#ifndef GGML_COMMIT
#define GGML_COMMIT "unknown"
#endif
EOF

find "$DEST" -name 'CMakeLists.txt' -delete
find "$DEST" -name '*.cmake' -delete
find "$DEST" -type d -empty -delete

echo "$TAG" > "$DEST/VERSION"
echo "vendored ggml ${GGML_MAJOR}.${GGML_MINOR}.${GGML_PATCH} (llama.cpp $TAG) into $DEST"
