#!/usr/bin/env bash
# Vendors whisper.cpp C/C++ sources into internal/whisper/cvendor/.
# Go shim files (*.go) and VERSION are preserved; everything else is synced
# from the upstream tag. ggml is vendored separately by scripts/vendor-ggml.sh
# into internal/ggml/cvendor/. Usage: scripts/vendor-whisper.sh [tag]
set -euo pipefail

TAG="${1:-v1.9.1}"
DEST="internal/whisper/cvendor"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

git clone --depth 1 --branch "$TAG" https://github.com/ggml-org/whisper.cpp "$TMP/w"

# Remove previously vendored C sources, keep our Go shims.
if [ -d "$DEST" ]; then
  find "$DEST" -type f ! -name '*.go' -delete
  find "$DEST" -type d -empty -delete
fi

mkdir -p "$DEST/include" "$DEST/src"

# Public headers (whisper.h, parakeet.h, ...).
cp "$TMP/w/include/"*.h "$DEST/include/"
find "$TMP/w/src" -maxdepth 1 -type f \( -name '*.cpp' -o -name '*.h' \) \
  -exec cp {} "$DEST/src/" \;

# Version macros are normally injected by CMake as compile definitions. cgo
# forbids '"' in #cgo flags, so we instead generate force-included headers
# (referenced via -include in the build.go shims) that carry the string
# literals. Values are parsed from the upstream tree so re-vendoring keeps them
# in sync.
WHISPER_VER="$(sed -n 's/.*project("whisper.cpp" VERSION \([0-9.]*\).*/\1/p' "$TMP/w/CMakeLists.txt")"

cat > "$DEST/src/whisper-version-defs.h" <<EOF
// Generated by scripts/vendor-whisper.sh. Do not edit.
#pragma once
#ifndef WHISPER_VERSION
#define WHISPER_VERSION "${WHISPER_VER}"
#endif
#ifndef PARAKEET_VERSION
#define PARAKEET_VERSION "${WHISPER_VER}"
#endif
EOF

# Strip build-system files that cgo must not see.
find "$DEST" -name 'CMakeLists.txt' -delete
find "$DEST" -name '*.cmake' -delete
# Drop directories left empty after stripping (e.g. cmake/ helper dirs).
find "$DEST" -type d -empty -delete

# Speech sample for the gated integration test.
mkdir -p internal/whisper/testdata
cp "$TMP/w/samples/jfk.wav" internal/whisper/testdata/jfk.wav

echo "$TAG" > "$DEST/VERSION"
echo "vendored whisper.cpp $TAG into $DEST"
