#!/usr/bin/env bash
# Vendors whisper.cpp C/C++ sources into internal/whisper/cvendor/.
# Go shim files (*.go) and VERSION are preserved; everything else is synced
# from the upstream tag. Usage: scripts/vendor-whisper.sh [tag]
set -euo pipefail

TAG="${1:-v1.9.1}"
DEST="internal/whisper/cvendor"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

git clone --depth 1 --branch "$TAG" https://github.com/ggml-org/whisper.cpp "$TMP/w"

# Remove previously vendored C sources, keep our Go shims.
if [ -d "$DEST" ]; then
  find "$DEST" -type f ! -name '*.go' -delete
  find "$DEST" -type d -empty -delete
fi

mkdir -p "$DEST/include" "$DEST/src" "$DEST/ggml/include" "$DEST/ggml/src"

# Public headers (whisper.h, parakeet.h, ...).
cp "$TMP/w/include/"*.h "$DEST/include/"
find "$TMP/w/src" -maxdepth 1 -type f \( -name '*.cpp' -o -name '*.h' \) \
  -exec cp {} "$DEST/src/" \;
cp "$TMP/w/ggml/include/"*.h "$DEST/ggml/include/"
find "$TMP/w/ggml/src" -maxdepth 1 -type f \
  \( -name '*.c' -o -name '*.cpp' -o -name '*.h' \) \
  -exec cp {} "$DEST/ggml/src/" \;

# CPU backend (and any subdirectories it has at this tag).
cp -r "$TMP/w/ggml/src/ggml-cpu" "$DEST/ggml/src/"

# Metal backend (darwin). Layout moved over time: directory or flat files.
if [ -d "$TMP/w/ggml/src/ggml-metal" ]; then
  cp -r "$TMP/w/ggml/src/ggml-metal" "$DEST/ggml/src/"
else
  mkdir -p "$DEST/ggml/src/ggml-metal"
  cp "$TMP/w/ggml/src/ggml-metal."* "$DEST/ggml/src/ggml-metal/" 2>/dev/null || true
fi

# Assembly stub that embeds the Metal shader source into the binary
# (GGML_METAL_EMBED_LIBRARY expects these symbols).
METAL_SRC="$(find "$DEST/ggml/src/ggml-metal" -name '*.metal' | head -1)"
if [ -n "$METAL_SRC" ]; then
  cat > "$DEST/ggml/src/ggml-metal/ggml-metal-embed.s" <<EOF
.section __DATA,__ggml_metallib
.globl _ggml_metallib_start
_ggml_metallib_start:
.incbin "$(basename "$METAL_SRC")"
.globl _ggml_metallib_end
_ggml_metallib_end:
EOF
fi

# Version macros are normally injected by CMake as compile definitions. cgo
# forbids '"' in #cgo flags, so we instead generate force-included headers
# (referenced via -include in the build.go shims) that carry the string
# literals. Values are parsed from the upstream tree so re-vendoring keeps them
# in sync.
GGML_MAJOR="$(grep -oP 'set\(GGML_VERSION_MAJOR \K[0-9]+' "$TMP/w/ggml/CMakeLists.txt")"
GGML_MINOR="$(grep -oP 'set\(GGML_VERSION_MINOR \K[0-9]+' "$TMP/w/ggml/CMakeLists.txt")"
GGML_PATCH="$(grep -oP 'set\(GGML_VERSION_PATCH \K[0-9]+' "$TMP/w/ggml/CMakeLists.txt")"
GGML_VER="${GGML_MAJOR}.${GGML_MINOR}.${GGML_PATCH}"
WHISPER_VER="$(grep -oP 'project\("whisper.cpp" VERSION \K[0-9.]+' "$TMP/w/CMakeLists.txt")"

cat > "$DEST/ggml/src/ggml-version-defs.h" <<EOF
// Generated by scripts/vendor-whisper.sh. Do not edit.
#pragma once
#ifndef GGML_VERSION
#define GGML_VERSION "${GGML_VER}"
#endif
#ifndef GGML_COMMIT
#define GGML_COMMIT "unknown"
#endif
EOF

cat > "$DEST/src/whisper-version-defs.h" <<EOF
// Generated by scripts/vendor-whisper.sh. Do not edit.
#pragma once
#ifndef WHISPER_VERSION
#define WHISPER_VERSION "${WHISPER_VER}"
#endif
#ifndef PARAKEET_VERSION
#define PARAKEET_VERSION "${WHISPER_VER}"
#endif
EOF

# Strip build-system files that cgo must not see.
find "$DEST" -name 'CMakeLists.txt' -delete
find "$DEST" -name '*.cmake' -delete
# Drop directories left empty after stripping (e.g. cmake/ helper dirs).
find "$DEST" -type d -empty -delete

# Speech sample for the gated integration test.
mkdir -p internal/whisper/testdata
cp "$TMP/w/samples/jfk.wav" internal/whisper/testdata/jfk.wav

echo "$TAG" > "$DEST/VERSION"
echo "vendored whisper.cpp $TAG into $DEST"
