#!/usr/bin/env bash
# Vendors whisper.cpp C/C++ sources into internal/whisper/cvendor/.
# Go shim files (*.go) and VERSION are preserved; everything else is synced
# from the upstream tag. Usage: scripts/vendor-whisper.sh [tag]
set -euo pipefail

TAG="${1:-v1.9.1}"
DEST="internal/whisper/cvendor"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

git clone --depth 1 --branch "$TAG" https://github.com/ggml-org/whisper.cpp "$TMP/w"

# Remove previously vendored C sources, keep our Go shims.
if [ -d "$DEST" ]; then
  find "$DEST" -type f ! -name '*.go' -delete
  find "$DEST" -type d -empty -delete
fi

mkdir -p "$DEST/include" "$DEST/src" "$DEST/ggml/include" "$DEST/ggml/src"

# Public headers (whisper.h, parakeet.h, ...).
cp "$TMP/w/include/"*.h "$DEST/include/"
find "$TMP/w/src" -maxdepth 1 -type f \( -name '*.cpp' -o -name '*.h' \) \
  -exec cp {} "$DEST/src/" \;
cp "$TMP/w/ggml/include/"*.h "$DEST/ggml/include/"
find "$TMP/w/ggml/src" -maxdepth 1 -type f \
  \( -name '*.c' -o -name '*.cpp' -o -name '*.h' \) \
  -exec cp {} "$DEST/ggml/src/" \;

# CPU backend (and any subdirectories it has at this tag).
cp -r "$TMP/w/ggml/src/ggml-cpu" "$DEST/ggml/src/"

# Metal backend (darwin). Layout moved over time: directory or flat files.
if [ -d "$TMP/w/ggml/src/ggml-metal" ]; then
  cp -r "$TMP/w/ggml/src/ggml-metal" "$DEST/ggml/src/"
else
  mkdir -p "$DEST/ggml/src/ggml-metal"
  cp "$TMP/w/ggml/src/ggml-metal."* "$DEST/ggml/src/ggml-metal/" 2>/dev/null || true
fi

# Assembly stub that embeds the Metal shader source into the binary
# (GGML_METAL_EMBED_LIBRARY expects these symbols). The embedded source is
# compiled by Metal at runtime with no include paths, so mirror upstream
# CMake: inline ggml-common.h at the __embed_ggml-common.h__ placeholder and
# inline ggml-metal-impl.h, producing a self-contained shader source.
METAL_SRC="$(find "$DEST/ggml/src/ggml-metal" -name 'ggml-metal.metal' | head -1)"
if [ -n "$METAL_SRC" ]; then
  METAL_DIR="$(dirname "$METAL_SRC")"
  sed -e "/__embed_ggml-common.h__/r $DEST/ggml/src/ggml-common.h" \
      -e '/__embed_ggml-common.h__/d' "$METAL_SRC" \
    | sed -e "/#include \"ggml-metal-impl.h\"/r $METAL_DIR/ggml-metal-impl.h" \
          -e '/#include "ggml-metal-impl.h"/d' \
    > "$METAL_DIR/ggml-metal-embed.metal"
  cat > "$METAL_DIR/ggml-metal-embed.s" <<EOF
.section __DATA,__ggml_metallib
.globl _ggml_metallib_start
_ggml_metallib_start:
.incbin "ggml-metal-embed.metal"
.globl _ggml_metallib_end
_ggml_metallib_end:
EOF
fi

# Version macros are normally injected by CMake as compile definitions. cgo
# forbids '"' in #cgo flags, so we instead generate force-included headers
# (referenced via -include in the build.go shims) that carry the string
# literals. Values are parsed from the upstream tree so re-vendoring keeps them
# in sync.
GGML_MAJOR="$(sed -n 's/.*set(GGML_VERSION_MAJOR \([0-9][0-9]*\)).*/\1/p' "$TMP/w/ggml/CMakeLists.txt")"
GGML_MINOR="$(sed -n 's/.*set(GGML_VERSION_MINOR \([0-9][0-9]*\)).*/\1/p' "$TMP/w/ggml/CMakeLists.txt")"
GGML_PATCH="$(sed -n 's/.*set(GGML_VERSION_PATCH \([0-9][0-9]*\)).*/\1/p' "$TMP/w/ggml/CMakeLists.txt")"
GGML_VER="${GGML_MAJOR}.${GGML_MINOR}.${GGML_PATCH}"
WHISPER_VER="$(sed -n 's/.*project("whisper.cpp" VERSION \([0-9.]*\).*/\1/p' "$TMP/w/CMakeLists.txt")"

cat > "$DEST/ggml/src/ggml-version-defs.h" <<EOF
// Generated by scripts/vendor-whisper.sh. Do not edit.
#pragma once
#ifndef GGML_VERSION
#define GGML_VERSION "${GGML_VER}"
#endif
#ifndef GGML_COMMIT
#define GGML_COMMIT "unknown"
#endif
EOF

cat > "$DEST/src/whisper-version-defs.h" <<EOF
// Generated by scripts/vendor-whisper.sh. Do not edit.
#pragma once
#ifndef WHISPER_VERSION
#define WHISPER_VERSION "${WHISPER_VER}"
#endif
#ifndef PARAKEET_VERSION
#define PARAKEET_VERSION "${WHISPER_VER}"
#endif
EOF

# Strip build-system files that cgo must not see.
find "$DEST" -name 'CMakeLists.txt' -delete
find "$DEST" -name '*.cmake' -delete
# Drop directories left empty after stripping (e.g. cmake/ helper dirs).
find "$DEST" -type d -empty -delete

# Speech sample for the gated integration test.
mkdir -p internal/whisper/testdata
cp "$TMP/w/samples/jfk.wav" internal/whisper/testdata/jfk.wav

echo "$TAG" > "$DEST/VERSION"
echo "vendored whisper.cpp $TAG into $DEST"
